### ISSUE TITLE
MM Configs and controller mappings reset after exit

### ISSUE THREAD

**Issue by Cozmo-S** [vitor251093/KHMelonMix#122]
Upon starting the program, all of my Config settings are reset—the aspect ratio, video & audio settings, and even my controller mappings. It’s quite annoying having to remap everything every time. I assume these would stay after being changed. Windows 10 btw.

**Comment by vitor251093** [comment]
The controller mapping being resetted is a known issue (#93), but the other ones, it's the first time I heard about that.

Is the melonDS.ini file being created properly next to the exe file?

**Comment by TheGershon** [comment]
I'll piggyback onto this.

Versions above 3.2 can't create a .toml file if they're within a path that contains non-standard characters (for instance, ∕ instead of / in order to have a forward slash in the folder title). Renaming the folder to let it create one and then renaming it back makes the .exe unable to launch.

**Comment by vitor251093** [comment]
We received no response for over 6 months, so we are closing this issue. It can be reopened if a new response appears, or if someone else reports the same problem
