### ISSUE TITLE
Side by side to fullscreen prerendered cutscenes produce black screen

### ISSUE THREAD

**Issue by GalacticVoid** [vitor251093/KHMelonMix#182]
After a pre-rendered cutscene transitions to being a side by side view, transitioning back to fullscreen creates a black screen with audio.

Intro cutscene as a result plays as follows:
Fullscreen (Fine) -> Side by Side (Fine) -> Fullscreen (IS A BLACK SCREEN WITH XEMNAS AUDIO ONLY) -> Side by side (Fine)

**To Reproduce**
It just happens to me when I play the opening cutscene.

**Expected behavior**
The side by side cutscene should transition back to a fullscreen cutscene with no issues.

(Audio distortion only present in recording, not an actual issue)
https://github.com/vitor251093/KHMelonMix/assets/26945375/92c53241-47e3-47c3-bac2-3a9cdb9671d2

 - OS: Windows 10
 - Melon Mix Version 0.3.2

**Comment by sandwichwater** [comment]
this is a known bug due to how scene detection is handled , the reason it happens like this is because the bottom screen turns black in the original , therefore affecting the top screen . you have probably also noticed that the top screen fades to black at the same time the organization info on the bottom screen does , this is because of the same thing

however , itll be fixed with cutscene replacement

**Comment by vitor251093** [comment]
> however , itll be fixed with cutscene replacement

This

**Comment by vitor251093** [comment]
Closing because this will be handled by #9
