### ISSUE TITLE
Black Pause Screen

### ISSUE THREAD

**Issue by RedDragoon101** [vitor251093/KHMelonMix#235]
On one of the Cutscenes in the "Investigate the Caves" Mission, pausing brings up a black screen.

Open Save, Do Mission, Get to Final Cutscene, Pause

Pause Menu should appear

![Screenshot (548)](https://github.com/user-attachments/assets/5ccad338-97ad-40ac-93eb-a72c0c09236e)
![Screenshot (549)](https://github.com/user-attachments/assets/609c1f44-1466-4941-9ef8-e80edec59894)

Here is Save: (Hopefully)
[Save.zip](https://github.com/user-attachments/files/16650963/Save.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: Latest Dev Build

**Comment by vitor251093** [comment]
It seems like the pause screen is being confused with the main menu, which is causing the bug.

I tried using memory detection, but it didn't work. I think that's because the pause from mission mode and from story mode are two different pause screens (one which pauses the game and shows the buttons, and one which shows the buttons without really pausing the game).

**Comment by vitor251093** [comment]
Fixed in the latest Actions build
