### ISSUE TITLE
Replace cutscenes with the remastered ones

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHMelonMix#9]
The cutscenes currently inside the game have a DS resolution. The best way to improve that would be by replacing them with their remastered counterparts.

I currently don't know how to do that, since I'm not even sure about the methods used to render the ingame cutscenes.

**Comment by sandwichwater** [comment]
i have a vague and rough idea of how to do this , im no expert in programming by any means but i do know quite a lot about the inner workings of this game

in short : the video codec hand used when developing the game is mobiclip , its logo can be seen partially on the splash screen 
, it was distributed in nintendos sdk for devs . the file is abbreviated as ".mods" (**MO**biclip for nintendo **DS**) in the "mv" folder of the game , ive messed around with various success in replacing the files directly but that requires hacking the game which would mean distributing a modified rom which is already a grey area , but also was done with nintendos dev tools which definitely cant be distributed since aquiring the liscense has you sign an nda saying you wont use it for rom hacks etc

anyways , now that ive got that summary out of the way , the best way i can think to do it would be to have the raw remastered videos stored in a folder , then call those videos to play over the ds cutscenes whenever the code for the .mods files is executed , would still have the decent ds audio quality but would have high quality video . im sure its not as easy as i made it sound but it shouldnt be impossible at all

**Comment by vitor251093** [comment]
I see. This is helpful to know indeed :)

But unfortunately, I've just researched to know more about Mobiclip, and it seems that their video codec only supports videos up to 240 pixels wide. 

https://wiki.multimedia.cx/index.php/Mobiclip_Video_Codec

I don't know if that's really the case, but if it's, I'm afraid the Mobiclip video codec may not be enough. Although, if that wiki is wrong, then maybe we can replace the video using a technique similar to the texture replacement, once it's fully implemented.

**Comment by vitor251093** [comment]
> > an idea , would it be possible to have a folder full of hd cutscenes and have a function or shader that calls those from the folder to play the video over the emulator when a prerendered cutscene is playing ¿ it would be a sortof hacky way of doing replacement seeing as it would just be playing video while the original game plays underneathe , but it might work
> 
> While that makes sense conceptually, I don't think it's possible to load a file from a shader. The shader can only perform calculations with whatever is given to it. Otherwise, it can't even access functions from the application itself.
> 
> With that being said, if I can provide the correct HD cutscene frame to it, it should be capable of replacing the original cutscene with it, but that leads us to the major problem: how to detect _which_ cutscene is playing?
> 
> It may be possible to discover that using the same technique I used to figure out the memory address of the in-game camera menu option, but I haven't tried that yet.
> 
> Although, maybe we should move this discussion to #9 , so we have one problem per issue.

**Comment by sandwichwater** [comment]
> With that being said, if I can provide the correct HD cutscene frame to it, it should be capable of replacing the original cutscene with it, but that leads us to the major problem: how to detect which cutscene is playing?

possibly could use the ID and offset addresses of the cutscenes ¿ for example the ID of the file "802.mods" (the opening cutscene) has an ID of 0x5CF and an offset of 0x8985400 , if those can be detected for each cutscene then a system of "if this matches these addresses then overlay cutscene1.mp4" may work ¿

**Comment by vitor251093** [comment]
That's correct. If we manage to figure out when a cutscene starts playing, we can play the video as soon as the cutscene starts.

And, if we keep a video player preloaded at all times, it should load the video fast enough to keep them in sync.

We would also need to stop the cutscene if the user skips it, possibly by simply stopping the reproduction of the cutscene if the ID is no longer being played.

The next step would be evaluating if we can (and if we should) replace cutscenes that originally were scripted dialogues, but which received HD cutscenes. But that will be sorted out by a different ticket, in the future.

Anyway, in order to detect when a video starts playing: we need to figure in which memory address the game stores the video ID (or the video offset) so we can figure out which video is playing, and when exactly that happens.

**Comment by vitor251093** [comment]
> for example the ID of the file "802.mods" (the opening cutscene) has an ID of 0x5CF and an offset of 0x8985400

Unfortunately, I couldn't find any of those while the opening cutscene was playing. At least during the execution of the cutscene. It's still possible that those may appear only when the cutscene is loaded into the memory

**Comment by sandwichwater** [comment]
hmm yea thats where theyre stored in the memory , i didnt think about the ones while the scene is playing , i wonder if that would be easier

**Comment by ZoopOTheGoop** [comment]
i looked into the Days cutscenes in the Epic Games release, and while `.mp4` files, they appear to have some sort of weird codec or missing header/metadata that makes them unplayable outside the game. Even `ffprobe`, which is usually extremely reliable, fails to load them. This is probably an incredibly easy fix to inject the proper metadata (scraping it from the executable maybe?), but that seems to be an added difficulty.

**Comment by CpazR** [comment]
Since the emulator absolutely cannot supply these assets itself. We would need some sort of tool to grab these files from the pc port install (and modify them as needed) and bundle them in such a way that the emulator can use them. 

At this point, it seems more likely that collaboration with OpenKH to help build this would be more phesable. I'd recommend hitting up the discord to see if anyone has done anything similar.

**Comment by vitor251093** [comment]
> At this point, it seems more likely that collaboration with OpenKH to help build this would be more phesable. I'd recommend hitting up the discord to see if anyone has done anything similar.

That does make sense. Although, I think that, before doing that, we need a reliable way to detect which cutscene is playing in-game. Otherwise, we may reach the capability of playing the remastered cutscenes without a clue about when to play them.

**Comment by mirh** [comment]
udta   }meta       Oilst   G©too   ?data       TMPGEnc MPEG Smart Renderer 4 Version 4.0.15.50   "hdlr        mdirappl             Àfree 

This is how the files end, it's not encrypted or stuff. It's just.. somehow the mp4 "parts" order is reversed?
https://www.exiftool.org/TagNames/QuickTime.html
https://xhelmboyx.tripod.com/formats/mp4-layout.txt
https://developer.apple.com/documentation/quicktime-file-format/chunk_offset_atom

Before that you have stuff like: tkhd, Sound Media Handler, mp4a
And right before: moov, mvhd, tkhd, mdia, Video Media Handler, avc1

**Comment by mirh** [comment]
The collection just got released on steam. 
I don't have it (and neither does [steamdb](https://steamdb.info/app/2552430/depots/)) but unless I missed some last minute change to wine/dxvk, they are probably shipping actually different video files altogether.

**Comment by sandwichwater** [comment]
although that is good to know , we still have the issue of not knowing how to get them to play ingame , obtaining the video files isnt really the problem , its getting them into the game . still , worth a look into the steam version though to see if theres any enhancements

**Comment by mirh** [comment]
Ok some gentleman must have gifted them the game, and they are [definitively](https://steamdb.info/depot/2552433/) \*at least\* [re-encoded](https://steamdb.info/depot/2552437/).
*By the way*, while I was at it I checked the ps4 files, and ironically enough they were plain mp4s (ftypisom, ftypmp42) all along. They play perfectly fine in VLC. 

The days movies still pretty much end up with the same string and structures that I posted above.. So I can eventually just guess the real problem with the original pc release was just that they removed the header from all the files.

**Comment by sandwichwater** [comment]
are there any differences in the days cutscenes at all ¿ if there are i might get the steam version and rip them , if not then we still have the epic files

**Comment by vitor251093** [comment]
> are there any differences in the days cutscenes at all ¿ if there are i might get the steam version and rip them , if not then we still have the epic files

According to what I learned recently, they are the same, but there is a bug across both versions that makes the cutscenes unplayable. @mirh may have just figured out why that is, so we may be able to fix the cutscenes upon loading them

**Comment by vitor251093** [comment]
@mirh is the header the same across all files? If so, would you mind sharing its hex?

**Comment by sandwichwater** [comment]
oh thats not a problem , i already have the epic files in a playable format

**Comment by vitor251093** [comment]
> oh thats not a problem , i already have the epic files in a playable format

But is there any way for us to make them playable programmatically? So we don't necessarily need to provide the cutscenes (only if the player doesn't have the collection)

**Comment by sandwichwater** [comment]
ohh , hmm good point , i didnt think about that🤔 that would probably be ideal yea

**Comment by ZoopOTheGoop** [comment]
Haven't cracked how they're being loaded yet, but table of addresses for movies, all are under the `mv` directory of the FAT filesystem of the ROM. The memory is based on the US ROM:

https://docs.google.com/spreadsheets/d/1kkoa__sBVF7AfwhHDRIBr-J_MBTxeWmb3jB-LSKJESY/

Later we can match them up with their HD counterparts. It should be noted that this excludes honestly probably 70% of the scenes that are in the HD version (there are almost no clocktower scenes in this list, for instance).

Also, the only known mobiclip decoders don't like these files and either strip the audio or garble it heavily, so most of the descriptions are based off memory of well-known scenes or the few bits of audio I could make out, they're just for reference purposes.

Next step I'm going to use desmume to watch these addresses to try and figure out how to tell if they're being loaded. I'd recommend making the other scenes a separate ticket, as it will involve a much more involved process of learning how scene transitions are handled and manually and laboriously playing through the game mapping Scene ID -> Cutscene.

**Comment by ZoopOTheGoop** [comment]
Also, it seems like the static effect that plays over the flashbacks of Sora's memories are done in-engine overlayed over the playing video - they're not encoded in the video files themselves, so we may have to contend with that if we attempt a replacement.

**Comment by ZoopOTheGoop** [comment]
Found it! Address 02093A4C holds the address of the playing cutscene. When not in a cutscene, it tends to be set to EA000000.

Caveats: this value will be set when the scene begins to play, but is not set to another value until control of Roxas resumes, so even in dialogue after the cutscene, it will still hold the address of the previous prerendered cutscene even after scene transitions.

**Comment by ZoopOTheGoop** [comment]
In terms of replacing the played videos, there's quite a lot of moving parts and would involve significant scripting on top of the game. Roughly, we'd have to hijack Melon when it detects a change to this address, manually play the cutscene in the window, and then basically feed an input to skip the original cutscene on after ours is done.

The raw HD videos also don't have subtitles burned in AFAIK so we might also have to do that on our own (which is a minor concern since we have to extract them from the PC releases anyway).

The primary issue is letting users skip the cutscene. Days doesn't allow pausing prerendered cutscenes, only skipping, so as a first pass it wouldn't be too hard to just have any button skip it like Days already does, but anything beyond that (and I predict this is a feature that would need to be in due to the huge QOL upgrade) - we start having to manually handle input in a way that's not immediately fed to the DS emulation during cutscene mode.

The _good_ news, is that 90% of this should still work for the cutscenes that replace in-engine cutscenes. When we learn how to detect those (which I'm working on) it's the exact same principle, it's just a different method to skip the original. So the setup for replacing the prerendered ones is effectively transferrable.

The _bad_ news is that i dont think the HD cutscenes have a great 1:1 correlation with the DS ones, from a quick glance there are multiple cutscenes in one that are single cutscenes in the other and vice versa - and this probably gets worse when you start taking in-engine ones into consideration. This isn't a deathknell for the idea, merely annoying. The _real_ hard work is going to be pulling in a video playback library and wiring it up to bypass the DS emulation on a memory trigger.

**Comment by mirh** [comment]
> According to what I learned recently, they are the same (Steam and Epic)

Yes, I guess they are the same. If you use the default windows branch. 
But on the steam deck (depot 2552437) they ship different movies. 

> is the header the same across all files? If so, would you mind sharing its hex?

It's very slightly different (of course? I mean, I think that's normal). But it's not hard to find the CUSA05786 files, and then extract it with fake pkg tools.

**Comment by vitor251093** [comment]
> The primary issue is letting users skip the cutscene. Days doesn't allow pausing prerendered cutscenes, only skipping, so as a first pass it wouldn't be too hard to just have any button skip it like Days already does, but anything beyond that (and I predict this is a feature that would need to be in due to the huge QOL upgrade) - we start having to manually handle input in a way that's not immediately fed to the DS emulation during cutscene mode. I suspect that's not the worst problem since there are already buttons that make UI elements appear and disappear that don't exist in the original release, but I want to make that step explicit.

Yeah, that won't really be that complicated. A d as a long term enhancement, we can implement the ability of pausing during cutscenes, by making the pause button pause the DS emulation instead, while the cutscene plays on top of it, and a fake pause screen is rendered on top of the cutscene. It would be a long term enhancement though.

> for instance, what if someone loads a savestate in the middle of one of the netherzones where the memory still points to a prerendered cutscene but its after skippig it

Since the original game doesn't have save/load states as a feature, I think we can make it functional, but without diving too much into it. Like, always reproducing the cutscene from start if the save state is loaded.

> But on the steam deck (depot 2552437) they ship different movies.
How different are them?

**Comment by mirh** [comment]
Well, they are a fourth the size for starters. 
Idk then, but given it's supposedly the only deck-specific fix they needed I'd expect at least a somewhat different file format.

**Comment by mirh** [comment]
Just for the absolute records some of [this](https://github.com/ValveSoftware/wine/compare/f80ddae9e217f2bad68455891371fa0f524451e7...d4688294816470922715aa522c2cb52cc1d02125) fixed the game on linux (and if I had to take a guess, it was specifically something [here](https://github.com/ValveSoftware/wine/compare/8d6dcef50fc084c560f3dc6cf5ceba1ca19b9835...d4688294816470922715aa522c2cb52cc1d02125#files_bucket)).. what to say?
Lots of stuff, including more support for transforms, conversions and *unsupported* formats themselves. 
Checking that *might* give some random insight into how the videos are coded, but you'd still eventually need some serious coding skill to come out with something usuable. 

So, really.. just use the `SteamDeck=1` variable and copy the videos (who knows if their quality is better or worse than the ps4 ones?) hoping that square won't decide to take down the branch in the future.

**Comment by ZLGNF** [comment]
@ZoopOTheGoop Is it possible to detect the Recoded dialogue scenes?

**Comment by ZoopOTheGoop** [comment]
probably, but im a bit slammed and can't check right now. i outlined my
method above if you want to give it a shot

**Comment by ZLGNF** [comment]
@ZoopOTheGoop 

I'm not sure if I'm doing this correctly at all but using the RAM Search on desmume it looks like these are the addresses that change when you are in and out of these scenes
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/04ed28f4-5d02-4e5a-99cf-8f136af25198)

**Comment by rarsneezes** [comment]
Clarification question: is this about replacing ALL cutscenes to be their HD Movie counterparts (including the textbox cutscenes), or just about replacing the like 12 already prerendered fully 3D/voiced cutscenes? 

I'm only asking because I prefer the textbox cutscenes over their movie counterparts, personally. Sorry if this has been asked before! Can't find it, and I felt like opening a whole new issue about it was silly.

**Comment by vitor251093** [comment]
> Clarification question: is this about replacing ALL cutscenes to be their HD Movie counterparts (including the textbox cutscenes), or just about replacing the like 12 already prerendered fully 3D/voiced cutscenes?
> 
> I'm only asking because I prefer the textbox cutscenes over their movie counterparts, personally. Sorry if this has been asked before! Can't find it, and I felt like opening a whole new issue about it was silly.

Replacing the DS cutscenes with HD counterparts.

In the future, if possible, we want to eventually replace the textbox ones as well, but either way, the code is being structured in a way that cutscenes will only be replaced if the HD replacement is available, so, if that ever happens, just keep the cutscenes whose name start with "hd8" in the assets/days/cutscenes folder, and delete the other ones.

**Comment by vitor251093** [comment]
Considering that, right now, we are dealing mostly with cutscene replacement bugs, while the mechanism itself works, I will merge this functionality to the master branch tonight, and then close this issue.

We will deal with further advancements and bug fixes on new issues.

**Comment by mirh** [comment]
See #184
